### ISSUE TITLE
Prevent crash when disconnecting a device during a transfer

### ISSUE THREAD

**Issue by motla** [tessel/node-usb#173]
Hello,

Thanks a lot for the library! I enjoy using it inside Electron and it works pretty well, beside the fact that I didn't found an example to handle errors as the USB device is disconnected during an InEndpoint transfer, using InEndpoint.transfer() or InEndpoint.poll(). The app simply crashes. Any help on this issue?

Romain

**Comment by kevinmehall** [comment]
You should get a callback with error `LIBUSB_NO_DEVICE` when the device is disconnected. What OS are you using?

**Comment by motla** [comment]
I'm using Win7 x64. Here are some details about my issue:

I'm also developing the firmware of the USB device, this is a custom HID device :
- 1 in Endpoint
- 1 out Endpoint
- both Interrupt transfers, both 128 bytes long (as defined in the HID report descriptor)

I made the firmware like this:
```
#define GET_STATUS_INFO 0xAA

void ManageOutEndpointEvent(uint8_t* out_report){

  switch(out_report[0]){ // out_report[0] is the instruction given by the PC

    case GET_STATUS_INFO:
       SendInEndpoint(some_status_info_array, 128);
       break;

    default:
       break;
  }
}
```
Now the Javascript looks like this:
```
const GET_STATUS_INFO = 0xAA;
var device = usb.findByIds(vid, pid);

if(device){
  device.open();
  var interface = device.interfaces[0];
  interface.claim();

  var inpoint = interface.endpoints[0]; // interface.endpoint(id) don't work for id=0 btw
  var outpoint = interface.endpoints[1];

  var update_status_info = function(){
    var out_report = Buffer.alloc(128, 0);
    out_report[0] = GET_STATUS_INFO;
    outpoint.transfer(out_report, function(err){
      if(err) throw err;

      inpoint.transfer(128, function(err, data){
        if(err) throw err;

        // valid data packet received!
        // ...

        // update status regulary
        setTimeout(update_status_info, 500);
      }
   }
}
```
Now everything works fine, but I have a chance that my app crashes when the USB device is unplugged, because some transfer is pending.

**So first question: is it the good workflow?**

I can also induce the same bug by simply calling like:
`inpoint.transfer(128, function(err, data){ if(err) throw err; console.log(data); });`
so the library is waiting for a transfer, the device is not responding, and then disconnecting the device.
The app crashes before any error is thrown.

Thanks a lot for your help! :+1: 
Romain

**Comment by kevinmehall** [comment]
That code looks fine to me and returns `LIBUSB_ERROR_NO_DEVICE` as expected in Node on Linux here. I suspect a bug in libusb's support for the Windows HID kernel driver. If you don't need device connect/disconnect events, you can try using the latest libusb (#161).

> interface.endpoint(id) don't work for id=0 btw

`interface.endpoint` looks up an endpoint by address. Only the control endpoint can have address 0, and it is exposed through `controlTransfer`, not an `Endpoint` object, so yes, I would expect `interface.endpoint(0)` to always fail.

**Comment by motla** [comment]
OK! Just read in both [libusb.org](http://libusb.org/wiki/FAQ#CanIcreateadriverlessdeviceusingHIDclass) and [libusb.info](https://github.com/libusb/libusb/wiki/FAQ#How_to_use_libusb_under_Windows) FAQs:

> If you require direct communication with a HID class device we recommend using the library ​HIDAPI by Signal 11 Software, which is also cross-platform.

So [node-hid](https://www.npmjs.com/package/node-hid) is a wrapper, and [usb-detection](https://www.npmjs.com/package/usb-detection) may be used for connect/disconnect events.
I'll try it and I keep you informed.

Thanks again for the help!

**Comment by motla** [comment]
Well I tested today with HIDAPI and it produces the exact same error!

**I never suspected Electron but it appears it's the culprit.**

I tested my code directly in Node CLI and LIBUSB_TRANSFER_ERROR is thrown correctly when device is disconnected. Whereas in Electron the current application window freezes and the developer tools window is untied: 
![image](https://cloud.githubusercontent.com/assets/16179413/23606870/e1fd0316-0262-11e7-8969-2fefa543489f.png)

So it's probably due to [electron-rebuild](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md). Or do you have a clue?

Apparently [someone experienced this on macOS](https://github.com/node-hid/node-hid/issues/153) as well.

Will report this to Electron.
Thanks

**Comment by markosole** [comment]
Hi guys, I am facing same problem on Windows 10 and Electron. My setup is on this link I've created: 
https://github.com/markosole/node-usb-barcode/blob/master/server.js

It's slightly different for usage in Electron & VUE app due to VUE requirements. 
Same thing happens for me, as @motla  described. 

@motla  did you find solution? - Maybe to try with refreshing app like soft restart? I haven't try that but will.

**Comment by motla** [comment]
@markosole No sorry, I moved from this project. Keep us in touch if you find something.

**Comment by markosole** [comment]
@motla Well here is what I have tried with success. Still needs some tweaks and bobs but I'll add that in a bit and test for longer time and see how it works.

I came up with Idea. If app has multiple processes you could use this procedure. Main process with your node-usb code and reading procedure. And second process which will only listen for device changes and restart second process (or part of the app, ex. windows). Basically, my app has index.js where window is defined, which is 99% in all Electron apps.

**I've added this on the top:**

    var usbDetect = require('usb-detection')
    usbDetect.startMonitoring()
    /* var vid = 0x1eab var pid = 0x0022 */
    usbDetect.on('change:7851:34', function(device) {
      console.log('change', device)
      mainWindow.reload()
    })

This will look for USB device changes and `reload()` windows I've specified. It can be any window.
Than, my node-usb is placed in other `myapp_window.js` file which depend on itself. 

When ever I pull USB cable out, app will go blank, but when I plug it back in it will `reload()` and start listening (open usb device and wait for data..). 
Next part is to wrap up node-usb part of the app with checks and run it only if specific device is available. This setup works for me as expected. It's not the best but... 

This will not work with just basic NodeJS app, because there is no windows. But.. Idea B) is to create and run two separate processes. One for checking the device status and that part will run / restart another .js process if USB device is added/removed. This needs to be tested.

**Comment by motla** [comment]
@markosole mighty! you found a great workaround.
It would definitely deserve some investigation at Electron's core but it's quite painful to recompile and setup a debug environment for Electron...

> This will not work with just basic NodeJS app, because there is no windows

No need to do that, NodeJS doesn't crash.

**Comment by markosole** [comment]
Sound ;) I'll try core NodeJS and in background service with forever module. I am using barcode scanner and processing is done in background. I believe this will be helpful to others with similar problems.
