### ISSUE TITLE
i want get string from usb-barcode-scanner

### ISSUE THREAD

**Issue by tihssiefiL** [tessel/node-usb#258]
i have no ieda to solve this problem by myself,i need help guys.
-------------------------------------------------------------------------------------------------------------------
    mainWindow.webContents.on('did-finish-load', () => {
        try {
            let device = usb.findByIds(1824, 12312)
            device.open()
            let interface = device.interfaces[0]
            interface.claim();
            let endpoint = interface.endpoints[0]
            mainWindow.webContents.send('main-process-messages', device);
            mainWindow.webContents.send('main-process-messages', interface);
            mainWindow.webContents.send('main-process-messages', endpoint);
            endpoint.startPoll(1, 8)
            console.log(endpoint.__proto__)
            console.log(endpoint.startPoll)
            endpoint.on('data', data => {
                mainWindow.webContents.send('main-process-messages', data);
                console.log(data)
            })
            endpoint.on('error', error => {
                console.log(error)
            })
            endpoint.on('end', end => {
                console.log(end)
            })
        } catch (error) {

        }
    })
-------------------------------------------------------------------------------------------------------------------
when i scan a barcode, the console does not print anything

**Comment by kevinmehall** [comment]
You need to know how the device communicates to write a driver for it. How did you determine that you want to read 8 byte packets from the first endpoint listed in the interface descriptor 0 of the device? Are you sure that's correct? Do you need to send any initialization commands first?

Take a close look at the output of `lsusb -v` on Linux. Does the device follow a standard USB protocol or is it vendor defined? If it's a standard class like HID or CDC-ACM, as is likely for a barcode scanner, you should use the existing OS drivers and a different library, rather than reimplementing with node-usb. If it's a nonstandard protocol, it's probably not documented, so you'll need to run the vendor-provided software, sniff its traffic, and reverse-engineer the protocol.
