### ISSUE TITLE
Implementation for Smart Cards

### ISSUE THREAD

**Issue by thundeR2GE** [tessel/node-usb#316]
I've been jumping around the internet for a few days and can't find a good solution for smart card data reading. I have a reader and card that are both detected by windows but into two categories (unsurprising) -Smart Card readers and -Smart cards. Can anyone assist me in trying to discover and read the data with this library? Thank you!

**Comment by kevinmehall** [comment]
[CCID](https://en.wikipedia.org/wiki/CCID_(protocol)) is the USB smart card class I've heard of. Wikipedia says Windows comes with drivers for CCID, no idea if there are existing Node bindings for those drivers. If you want to read the [CCID spec](https://www.usb.org/sites/default/files/DWG_Smart-Card_CCID_Rev110.pdf) and write your own driver in JS, you could bind the device to WinUSB instead of Windows'  default CCID driver and use this library.
