### ISSUE TITLE
Writing to usb controller does nothing until manually echoing

### ISSUE THREAD

**Issue by Awoogamuffin** [tessel/node-usb#327]
This is quite strange – I thought the code I was using to send a simple signal, any signal, to usb controller (whose function is to open a cash drawer) wasn't working.

This is on an ubuntu machine, and this is the code in question (in typescript):

`openDrawer(d: usb.Device) {
    d.open();
    const iFace: usb.Interface = d.interface(0);
    // detach kernal driver if necessary
    if (iFace.isKernelDriverActive()) {
        iFace.detachKernelDriver();
    }
    iFace.claim();
    // I could write a loop to specifically find the OutEndpoint for this device, but I know it is at position 1
    const outEndPoint: usb.OutEndpoint = iFace.endpoints[1] as usb.OutEndpoint;
    outEndPoint.transfer(new Buffer(1), (err) => {
        console.log('transfer finished');
        if (err) {
            console.warn('TRANSFER ERROR', err);
        }
        iFace.release((err) => {
            if (err) {
                console.warn('RELEASE ERROR', err);
            }
            console.log('reattaching');
            iFace.attachKernelDriver();
            d.close();
        });   
    });
}`

No errors, but also no cash drawer opening.

I wanted to check that the usb controller was actually running, and after checking that the device could be found at /dev/ttyUSB0. So I tried the following just to check the drawer was working:

`sudo chmod o+rw /dev/ttyUSB0
sudo echo '1' > /dev/ttyUSB0`

And the drawer did indeed open.

But what's weird now is that the typescript code above was working now too! I could reliably open the drawer by running that function. Somehow echoing the '1' to /dev/ttyUSB0 "unlocked" that device for typescript code to work. Unplugging the device and plugging it back, however, returned it to its dormant state. Same for restarting the machine.

Any idea why this might be? If you want stackoverflow points, I've put the question there too:

https://stackoverflow.com/questions/58043799/cant-write-to-usb-device-using-node-usb-until-manually-doing-so-using-echo

**Comment by kevinmehall** [comment]
If your device is a USB serial port, you should use `node-serialport` to use the kernel serial drivers instead. With `node-usb`, you'd have to implement the FTDI or CDC-ACM or whatever protocol to configure the serial port before writing to the device. When you are writing to the port through the kernel driver, it is performing the initialization for you. This library is intended for implementing drivers for USB devices in Node, but since the kernel already has a driver for your device, you should use a library that interfaces with that driver.
