### ISSUE TITLE
LIBUSB_ERROR_IO - usbfs: process 12689 (node) did not claim interface 0 before use

### ISSUE THREAD

**Issue by robertmain** [tessel/node-usb#363]
I'm trying to interact with a USB camera using [a library](https://www.npmjs.com/package/uvc-control2) which in turn uses node-usb. The issue is that attempts to "open" the USB device produce a `LIBUSB_ERROR_IO` exception, and I see `usbfs: process 12689 (node) did not claim interface 0 before use` in `dmesg`(I'm on Linux). 

I have a udev rule in `/etc/udev/rules.d/80-webcam.rules` which looks like this:

```
SUBSYSTEM=="usb" \
, GROUP="plugdev"
, MODE="0666"
```

My user is in the `plugdev` group, and this still seems to happen if I run my code as `root`(for debugging purposes). It seemed like it might be related to #25, but I'm not sure.

**Comment by kevinmehall** [comment]
That dmesg log is the kernel is complaining that the library is sending control transfers targeting the interface without [claiming](https://github.com/tessel/node-usb#claim) the interface. However, you'll probably be unable to claim the interface because it will already be claimed by the UVC kernel driver, which you're presumably using to stream the actual video from the device. What that library is doing is inherently dangerous manipulating the device state behind the kernel driver's back, and on macOS and Windows which are more strict, you'd have to choose one driver or the other.

The LIBUSB_ERROR_IO is more likely to be related to that than a permissions problem. It's unlikely that it's the same problem the person in #25 was hitting, but my suggestion for troubleshooting it there is my suggestion for you as well.

> [usbmon](https://www.kernel.org/doc/Documentation/usb/usbmon.txt) is probably your best bet for debugging to see what's actually being sent and what the kernel's error code is. The kernel error codes are more specific than the libusb error codes, but are only [somewhat documented](https://www.kernel.org/doc/Documentation/usb/error-codes.txt) 

I'll add that the `errno` command can be used to look up the names of the error codes from the numbers in the usbmon log.
