### ISSUE TITLE
Is it possible to detect usb devices in docker/balena container ?

### ISSUE THREAD

**Issue by adamvx** [tessel/node-usb#393]
Hi,

I tried to implement this library for my project running on balena but I was not able to make it run. It works on host but not in container even when its started with privileged flag. 

I can provide an example to try it out. 

First run the test container.
`docker run -it --name test --privileged balenalib/raspberrypi4-64-debian-node:11-buster-build bash`

Then create and new folder with `mkdir app` and inside it create new project with `npm init -y` 

Install required package with `install_packages libudev-dev` and install this library `npm i usb`. This will take some time because on this specific image are no pre-builded binaries

Then create index.js `touch index.js` and paste there this snippet.
```
var usb = require('usb');

console.log('Listening...');

usb.on('attach', (device) => {
    console.log(device);
});

usb.on('detach', (device) => {
    console.log(device);
});
```

Finally run project with `node index.js` and try to connect or disconnect any usb device. I was not able to detect any device even if its present in `/dev` directory inside the container.

Does anyone has been solving similar issue or is there some guide that I am not aware of ? 

Thanks for the help.

**Comment by mildsunrise** [comment]
I would advise against containers if you need to integrate with hardware (unless it's a very small and well defined subset). You'll get a _lot_ of headaches, because the illusion that every container has its own kernel starts to break.

hotplug detection (what you're trying to do) is accomplished by libusb in two ways: either by talking to udev, or if not available, by talking to the kernel directly over Netlink / uevent (but this requires root). (this is the official version; the libusb used by this module is fairly old, so I don't know)

There is no udev deamon running inside your container, so it can't possibly work. You could investigate how udev works, and expose the necessary sockets / whatever to the container. You could also run a full container (with its own init system, udev, etc.) and it could work too. Or you could compile libusb without `HAVE_LIBUDEV` so that it uses Netlink directly.
